import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import PageTransitionWrapper from '@/components/pageTransition/PageTransitionWrapper';
import './globals.scss';

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-inter',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body>
        <PageTransitionWrapper>
          <main>{children}</main>
        </PageTransitionWrapper>
      </body>
    </html>
  );
}
